language: java
sudo: false
install: true
jdk: oraclejdk7
script: ./travis.sh

env:
  - JOB=ITS IT_CATEGORY=server_updatecenter UNUSED=1
  - JOB=ITS IT_CATEGORY=server_updatecenter UNUSED=2
  - JOB=ITS IT_CATEGORY=server_updatecenter UNUSED=3
  - JOB=ITS IT_CATEGORY=server_updatecenter UNUSED=4
  - JOB=ITS IT_CATEGORY=server_updatecenter UNUSED=5
  - JOB=ITS IT_CATEGORY=server_updatecenter UNUSED=6
  - JOB=ITS IT_CATEGORY=server_updatecenter UNUSED=7
  - JOB=ITS IT_CATEGORY=server_updatecenter UNUSED=7
  - JOB=ITS IT_CATEGORY=server_updatecenter UNUSED=9

matrix:
  fast_finish: true

cache:
  directories:
    - '$HOME/.m2/repository'
    - 'server/sonar-web/node'
    - 'server/sonar-web/node_modules'

before_cache:
  - 'find ~/.m2/repository -type d -name \*-SNAPSHOT -exec rm -rf {} \;'
  - 'find ~/.m2/repository -name maven-metadata-\* -exec rm {} \;'
  - 'find ~/.m2/repository -name resolver-status.properties -exec rm {} \;'

notifications:
  email: false
