// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ws-ce.proto

package org.sonarqube.ws;

public final class WsCe {
  private WsCe() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code sonarqube.ws.ce.TaskStatus}
   */
  public enum TaskStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PENDING = 0;</code>
     */
    PENDING(0, 0),
    /**
     * <code>IN_PROGRESS = 1;</code>
     */
    IN_PROGRESS(1, 1),
    /**
     * <code>SUCCESS = 2;</code>
     */
    SUCCESS(2, 2),
    /**
     * <code>FAILED = 3;</code>
     */
    FAILED(3, 3),
    /**
     * <code>CANCELED = 4;</code>
     */
    CANCELED(4, 4),
    UNRECOGNIZED(-1, -1),
    ;

    /**
     * <code>PENDING = 0;</code>
     */
    public static final int PENDING_VALUE = 0;
    /**
     * <code>IN_PROGRESS = 1;</code>
     */
    public static final int IN_PROGRESS_VALUE = 1;
    /**
     * <code>SUCCESS = 2;</code>
     */
    public static final int SUCCESS_VALUE = 2;
    /**
     * <code>FAILED = 3;</code>
     */
    public static final int FAILED_VALUE = 3;
    /**
     * <code>CANCELED = 4;</code>
     */
    public static final int CANCELED_VALUE = 4;


    public final int getNumber() {
      if (index == -1) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    public static TaskStatus valueOf(int value) {
      switch (value) {
        case 0: return PENDING;
        case 1: return IN_PROGRESS;
        case 2: return SUCCESS;
        case 3: return FAILED;
        case 4: return CANCELED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TaskStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<TaskStatus>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TaskStatus>() {
            public TaskStatus findValueByNumber(int number) {
              return TaskStatus.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.sonarqube.ws.WsCe.getDescriptor().getEnumTypes().get(0);
    }

    private static final TaskStatus[] VALUES = values();

    public static TaskStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private TaskStatus(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:sonarqube.ws.ce.TaskStatus)
  }

  public interface SubmitResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sonarqube.ws.ce.SubmitResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string taskId = 1;</code>
     */
    java.lang.String getTaskId();
    /**
     * <code>optional string taskId = 1;</code>
     */
    com.google.protobuf.ByteString
        getTaskIdBytes();
  }
  /**
   * Protobuf type {@code sonarqube.ws.ce.SubmitResponse}
   *
   * <pre>
   * POST api/ce/submit
   * </pre>
   */
  public  static final class SubmitResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:sonarqube.ws.ce.SubmitResponse)
      SubmitResponseOrBuilder {
    // Use SubmitResponse.newBuilder() to construct.
    private SubmitResponse(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private SubmitResponse() {
      taskId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SubmitResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();

              taskId_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.sonarqube.ws.WsCe.internal_static_sonarqube_ws_ce_SubmitResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.sonarqube.ws.WsCe.internal_static_sonarqube_ws_ce_SubmitResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.sonarqube.ws.WsCe.SubmitResponse.class, org.sonarqube.ws.WsCe.SubmitResponse.Builder.class);
    }

    public static final int TASKID_FIELD_NUMBER = 1;
    private volatile java.lang.Object taskId_;
    /**
     * <code>optional string taskId = 1;</code>
     */
    public java.lang.String getTaskId() {
      java.lang.Object ref = taskId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          taskId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string taskId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTaskIdBytes() {
      java.lang.Object ref = taskId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTaskIdBytes().isEmpty()) {
        output.writeBytes(1, getTaskIdBytes());
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTaskIdBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTaskIdBytes());
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static org.sonarqube.ws.WsCe.SubmitResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sonarqube.ws.WsCe.SubmitResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sonarqube.ws.WsCe.SubmitResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sonarqube.ws.WsCe.SubmitResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sonarqube.ws.WsCe.SubmitResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.sonarqube.ws.WsCe.SubmitResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.sonarqube.ws.WsCe.SubmitResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.sonarqube.ws.WsCe.SubmitResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.sonarqube.ws.WsCe.SubmitResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.sonarqube.ws.WsCe.SubmitResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.sonarqube.ws.WsCe.SubmitResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sonarqube.ws.ce.SubmitResponse}
     *
     * <pre>
     * POST api/ce/submit
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sonarqube.ws.ce.SubmitResponse)
        org.sonarqube.ws.WsCe.SubmitResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.sonarqube.ws.WsCe.internal_static_sonarqube_ws_ce_SubmitResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.sonarqube.ws.WsCe.internal_static_sonarqube_ws_ce_SubmitResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.sonarqube.ws.WsCe.SubmitResponse.class, org.sonarqube.ws.WsCe.SubmitResponse.Builder.class);
      }

      // Construct using org.sonarqube.ws.WsCe.SubmitResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        taskId_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.sonarqube.ws.WsCe.internal_static_sonarqube_ws_ce_SubmitResponse_descriptor;
      }

      public org.sonarqube.ws.WsCe.SubmitResponse getDefaultInstanceForType() {
        return org.sonarqube.ws.WsCe.SubmitResponse.getDefaultInstance();
      }

      public org.sonarqube.ws.WsCe.SubmitResponse build() {
        org.sonarqube.ws.WsCe.SubmitResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.sonarqube.ws.WsCe.SubmitResponse buildPartial() {
        org.sonarqube.ws.WsCe.SubmitResponse result = new org.sonarqube.ws.WsCe.SubmitResponse(this);
        result.taskId_ = taskId_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.sonarqube.ws.WsCe.SubmitResponse) {
          return mergeFrom((org.sonarqube.ws.WsCe.SubmitResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.sonarqube.ws.WsCe.SubmitResponse other) {
        if (other == org.sonarqube.ws.WsCe.SubmitResponse.getDefaultInstance()) return this;
        if (!other.getTaskId().isEmpty()) {
          taskId_ = other.taskId_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.sonarqube.ws.WsCe.SubmitResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.sonarqube.ws.WsCe.SubmitResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object taskId_ = "";
      /**
       * <code>optional string taskId = 1;</code>
       */
      public java.lang.String getTaskId() {
        java.lang.Object ref = taskId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            taskId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string taskId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTaskIdBytes() {
        java.lang.Object ref = taskId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          taskId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string taskId = 1;</code>
       */
      public Builder setTaskId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        taskId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string taskId = 1;</code>
       */
      public Builder clearTaskId() {
        
        taskId_ = getDefaultInstance().getTaskId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string taskId = 1;</code>
       */
      public Builder setTaskIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        taskId_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:sonarqube.ws.ce.SubmitResponse)
    }

    // @@protoc_insertion_point(class_scope:sonarqube.ws.ce.SubmitResponse)
    private static final org.sonarqube.ws.WsCe.SubmitResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.sonarqube.ws.WsCe.SubmitResponse();
    }

    public static org.sonarqube.ws.WsCe.SubmitResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<SubmitResponse> PARSER =
        new com.google.protobuf.AbstractParser<SubmitResponse>() {
      public SubmitResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new SubmitResponse(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SubmitResponse> getParserForType() {
      return PARSER;
    }

    public org.sonarqube.ws.WsCe.SubmitResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TaskResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sonarqube.ws.ce.TaskResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>optional string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>optional string taskType = 2;</code>
     */
    java.lang.String getTaskType();
    /**
     * <code>optional string taskType = 2;</code>
     */
    com.google.protobuf.ByteString
        getTaskTypeBytes();

    /**
     * <code>optional string componentId = 3;</code>
     */
    java.lang.String getComponentId();
    /**
     * <code>optional string componentId = 3;</code>
     */
    com.google.protobuf.ByteString
        getComponentIdBytes();

    /**
     * <code>optional string componentKey = 4;</code>
     */
    java.lang.String getComponentKey();
    /**
     * <code>optional string componentKey = 4;</code>
     */
    com.google.protobuf.ByteString
        getComponentKeyBytes();

    /**
     * <code>optional string componentName = 5;</code>
     */
    java.lang.String getComponentName();
    /**
     * <code>optional string componentName = 5;</code>
     */
    com.google.protobuf.ByteString
        getComponentNameBytes();

    /**
     * <code>optional .sonarqube.ws.ce.TaskStatus status = 6;</code>
     */
    int getStatusValue();
    /**
     * <code>optional .sonarqube.ws.ce.TaskStatus status = 6;</code>
     */
    org.sonarqube.ws.WsCe.TaskStatus getStatus();

    /**
     * <code>optional string submittedAt = 7;</code>
     */
    java.lang.String getSubmittedAt();
    /**
     * <code>optional string submittedAt = 7;</code>
     */
    com.google.protobuf.ByteString
        getSubmittedAtBytes();

    /**
     * <code>optional string submitterLogin = 8;</code>
     */
    java.lang.String getSubmitterLogin();
    /**
     * <code>optional string submitterLogin = 8;</code>
     */
    com.google.protobuf.ByteString
        getSubmitterLoginBytes();

    /**
     * <code>optional string startedAt = 9;</code>
     */
    java.lang.String getStartedAt();
    /**
     * <code>optional string startedAt = 9;</code>
     */
    com.google.protobuf.ByteString
        getStartedAtBytes();

    /**
     * <code>optional string finishedAt = 10;</code>
     */
    java.lang.String getFinishedAt();
    /**
     * <code>optional string finishedAt = 10;</code>
     */
    com.google.protobuf.ByteString
        getFinishedAtBytes();

    /**
     * <code>optional bool isLastFinished = 11;</code>
     */
    boolean getIsLastFinished();

    /**
     * <code>optional int64 executionTimeMs = 12;</code>
     */
    long getExecutionTimeMs();
  }
  /**
   * Protobuf type {@code sonarqube.ws.ce.TaskResponse}
   *
   * <pre>
   * GET api/ce/task
   * </pre>
   */
  public  static final class TaskResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:sonarqube.ws.ce.TaskResponse)
      TaskResponseOrBuilder {
    // Use TaskResponse.newBuilder() to construct.
    private TaskResponse(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private TaskResponse() {
      id_ = "";
      taskType_ = "";
      componentId_ = "";
      componentKey_ = "";
      componentName_ = "";
      status_ = 0;
      submittedAt_ = "";
      submitterLogin_ = "";
      startedAt_ = "";
      finishedAt_ = "";
      isLastFinished_ = false;
      executionTimeMs_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TaskResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();

              id_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();

              taskType_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();

              componentId_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();

              componentKey_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();

              componentName_ = bs;
              break;
            }
            case 48: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();

              submittedAt_ = bs;
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();

              submitterLogin_ = bs;
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();

              startedAt_ = bs;
              break;
            }
            case 82: {
              com.google.protobuf.ByteString bs = input.readBytes();

              finishedAt_ = bs;
              break;
            }
            case 88: {

              isLastFinished_ = input.readBool();
              break;
            }
            case 96: {

              executionTimeMs_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.sonarqube.ws.WsCe.internal_static_sonarqube_ws_ce_TaskResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.sonarqube.ws.WsCe.internal_static_sonarqube_ws_ce_TaskResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.sonarqube.ws.WsCe.TaskResponse.class, org.sonarqube.ws.WsCe.TaskResponse.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>optional string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TASKTYPE_FIELD_NUMBER = 2;
    private volatile java.lang.Object taskType_;
    /**
     * <code>optional string taskType = 2;</code>
     */
    public java.lang.String getTaskType() {
      java.lang.Object ref = taskType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          taskType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string taskType = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTaskTypeBytes() {
      java.lang.Object ref = taskType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMPONENTID_FIELD_NUMBER = 3;
    private volatile java.lang.Object componentId_;
    /**
     * <code>optional string componentId = 3;</code>
     */
    public java.lang.String getComponentId() {
      java.lang.Object ref = componentId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          componentId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string componentId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getComponentIdBytes() {
      java.lang.Object ref = componentId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        componentId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMPONENTKEY_FIELD_NUMBER = 4;
    private volatile java.lang.Object componentKey_;
    /**
     * <code>optional string componentKey = 4;</code>
     */
    public java.lang.String getComponentKey() {
      java.lang.Object ref = componentKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          componentKey_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string componentKey = 4;</code>
     */
    public com.google.protobuf.ByteString
        getComponentKeyBytes() {
      java.lang.Object ref = componentKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        componentKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMPONENTNAME_FIELD_NUMBER = 5;
    private volatile java.lang.Object componentName_;
    /**
     * <code>optional string componentName = 5;</code>
     */
    public java.lang.String getComponentName() {
      java.lang.Object ref = componentName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          componentName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string componentName = 5;</code>
     */
    public com.google.protobuf.ByteString
        getComponentNameBytes() {
      java.lang.Object ref = componentName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        componentName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 6;
    private int status_;
    /**
     * <code>optional .sonarqube.ws.ce.TaskStatus status = 6;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>optional .sonarqube.ws.ce.TaskStatus status = 6;</code>
     */
    public org.sonarqube.ws.WsCe.TaskStatus getStatus() {
      org.sonarqube.ws.WsCe.TaskStatus result = org.sonarqube.ws.WsCe.TaskStatus.valueOf(status_);
      return result == null ? org.sonarqube.ws.WsCe.TaskStatus.UNRECOGNIZED : result;
    }

    public static final int SUBMITTEDAT_FIELD_NUMBER = 7;
    private volatile java.lang.Object submittedAt_;
    /**
     * <code>optional string submittedAt = 7;</code>
     */
    public java.lang.String getSubmittedAt() {
      java.lang.Object ref = submittedAt_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          submittedAt_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string submittedAt = 7;</code>
     */
    public com.google.protobuf.ByteString
        getSubmittedAtBytes() {
      java.lang.Object ref = submittedAt_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        submittedAt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUBMITTERLOGIN_FIELD_NUMBER = 8;
    private volatile java.lang.Object submitterLogin_;
    /**
     * <code>optional string submitterLogin = 8;</code>
     */
    public java.lang.String getSubmitterLogin() {
      java.lang.Object ref = submitterLogin_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          submitterLogin_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string submitterLogin = 8;</code>
     */
    public com.google.protobuf.ByteString
        getSubmitterLoginBytes() {
      java.lang.Object ref = submitterLogin_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        submitterLogin_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STARTEDAT_FIELD_NUMBER = 9;
    private volatile java.lang.Object startedAt_;
    /**
     * <code>optional string startedAt = 9;</code>
     */
    public java.lang.String getStartedAt() {
      java.lang.Object ref = startedAt_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          startedAt_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string startedAt = 9;</code>
     */
    public com.google.protobuf.ByteString
        getStartedAtBytes() {
      java.lang.Object ref = startedAt_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        startedAt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FINISHEDAT_FIELD_NUMBER = 10;
    private volatile java.lang.Object finishedAt_;
    /**
     * <code>optional string finishedAt = 10;</code>
     */
    public java.lang.String getFinishedAt() {
      java.lang.Object ref = finishedAt_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          finishedAt_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string finishedAt = 10;</code>
     */
    public com.google.protobuf.ByteString
        getFinishedAtBytes() {
      java.lang.Object ref = finishedAt_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        finishedAt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISLASTFINISHED_FIELD_NUMBER = 11;
    private boolean isLastFinished_;
    /**
     * <code>optional bool isLastFinished = 11;</code>
     */
    public boolean getIsLastFinished() {
      return isLastFinished_;
    }

    public static final int EXECUTIONTIMEMS_FIELD_NUMBER = 12;
    private long executionTimeMs_;
    /**
     * <code>optional int64 executionTimeMs = 12;</code>
     */
    public long getExecutionTimeMs() {
      return executionTimeMs_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        output.writeBytes(1, getIdBytes());
      }
      if (!getTaskTypeBytes().isEmpty()) {
        output.writeBytes(2, getTaskTypeBytes());
      }
      if (!getComponentIdBytes().isEmpty()) {
        output.writeBytes(3, getComponentIdBytes());
      }
      if (!getComponentKeyBytes().isEmpty()) {
        output.writeBytes(4, getComponentKeyBytes());
      }
      if (!getComponentNameBytes().isEmpty()) {
        output.writeBytes(5, getComponentNameBytes());
      }
      if (status_ != org.sonarqube.ws.WsCe.TaskStatus.PENDING.getNumber()) {
        output.writeEnum(6, status_);
      }
      if (!getSubmittedAtBytes().isEmpty()) {
        output.writeBytes(7, getSubmittedAtBytes());
      }
      if (!getSubmitterLoginBytes().isEmpty()) {
        output.writeBytes(8, getSubmitterLoginBytes());
      }
      if (!getStartedAtBytes().isEmpty()) {
        output.writeBytes(9, getStartedAtBytes());
      }
      if (!getFinishedAtBytes().isEmpty()) {
        output.writeBytes(10, getFinishedAtBytes());
      }
      if (isLastFinished_ != false) {
        output.writeBool(11, isLastFinished_);
      }
      if (executionTimeMs_ != 0L) {
        output.writeInt64(12, executionTimeMs_);
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (!getTaskTypeBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTaskTypeBytes());
      }
      if (!getComponentIdBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getComponentIdBytes());
      }
      if (!getComponentKeyBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getComponentKeyBytes());
      }
      if (!getComponentNameBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getComponentNameBytes());
      }
      if (status_ != org.sonarqube.ws.WsCe.TaskStatus.PENDING.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, status_);
      }
      if (!getSubmittedAtBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getSubmittedAtBytes());
      }
      if (!getSubmitterLoginBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getSubmitterLoginBytes());
      }
      if (!getStartedAtBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getStartedAtBytes());
      }
      if (!getFinishedAtBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getFinishedAtBytes());
      }
      if (isLastFinished_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(11, isLastFinished_);
      }
      if (executionTimeMs_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(12, executionTimeMs_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static org.sonarqube.ws.WsCe.TaskResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sonarqube.ws.WsCe.TaskResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sonarqube.ws.WsCe.TaskResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sonarqube.ws.WsCe.TaskResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sonarqube.ws.WsCe.TaskResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.sonarqube.ws.WsCe.TaskResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.sonarqube.ws.WsCe.TaskResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.sonarqube.ws.WsCe.TaskResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.sonarqube.ws.WsCe.TaskResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.sonarqube.ws.WsCe.TaskResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.sonarqube.ws.WsCe.TaskResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sonarqube.ws.ce.TaskResponse}
     *
     * <pre>
     * GET api/ce/task
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sonarqube.ws.ce.TaskResponse)
        org.sonarqube.ws.WsCe.TaskResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.sonarqube.ws.WsCe.internal_static_sonarqube_ws_ce_TaskResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.sonarqube.ws.WsCe.internal_static_sonarqube_ws_ce_TaskResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.sonarqube.ws.WsCe.TaskResponse.class, org.sonarqube.ws.WsCe.TaskResponse.Builder.class);
      }

      // Construct using org.sonarqube.ws.WsCe.TaskResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = "";

        taskType_ = "";

        componentId_ = "";

        componentKey_ = "";

        componentName_ = "";

        status_ = 0;

        submittedAt_ = "";

        submitterLogin_ = "";

        startedAt_ = "";

        finishedAt_ = "";

        isLastFinished_ = false;

        executionTimeMs_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.sonarqube.ws.WsCe.internal_static_sonarqube_ws_ce_TaskResponse_descriptor;
      }

      public org.sonarqube.ws.WsCe.TaskResponse getDefaultInstanceForType() {
        return org.sonarqube.ws.WsCe.TaskResponse.getDefaultInstance();
      }

      public org.sonarqube.ws.WsCe.TaskResponse build() {
        org.sonarqube.ws.WsCe.TaskResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.sonarqube.ws.WsCe.TaskResponse buildPartial() {
        org.sonarqube.ws.WsCe.TaskResponse result = new org.sonarqube.ws.WsCe.TaskResponse(this);
        result.id_ = id_;
        result.taskType_ = taskType_;
        result.componentId_ = componentId_;
        result.componentKey_ = componentKey_;
        result.componentName_ = componentName_;
        result.status_ = status_;
        result.submittedAt_ = submittedAt_;
        result.submitterLogin_ = submitterLogin_;
        result.startedAt_ = startedAt_;
        result.finishedAt_ = finishedAt_;
        result.isLastFinished_ = isLastFinished_;
        result.executionTimeMs_ = executionTimeMs_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.sonarqube.ws.WsCe.TaskResponse) {
          return mergeFrom((org.sonarqube.ws.WsCe.TaskResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.sonarqube.ws.WsCe.TaskResponse other) {
        if (other == org.sonarqube.ws.WsCe.TaskResponse.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getTaskType().isEmpty()) {
          taskType_ = other.taskType_;
          onChanged();
        }
        if (!other.getComponentId().isEmpty()) {
          componentId_ = other.componentId_;
          onChanged();
        }
        if (!other.getComponentKey().isEmpty()) {
          componentKey_ = other.componentKey_;
          onChanged();
        }
        if (!other.getComponentName().isEmpty()) {
          componentName_ = other.componentName_;
          onChanged();
        }
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        if (!other.getSubmittedAt().isEmpty()) {
          submittedAt_ = other.submittedAt_;
          onChanged();
        }
        if (!other.getSubmitterLogin().isEmpty()) {
          submitterLogin_ = other.submitterLogin_;
          onChanged();
        }
        if (!other.getStartedAt().isEmpty()) {
          startedAt_ = other.startedAt_;
          onChanged();
        }
        if (!other.getFinishedAt().isEmpty()) {
          finishedAt_ = other.finishedAt_;
          onChanged();
        }
        if (other.getIsLastFinished() != false) {
          setIsLastFinished(other.getIsLastFinished());
        }
        if (other.getExecutionTimeMs() != 0L) {
          setExecutionTimeMs(other.getExecutionTimeMs());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.sonarqube.ws.WsCe.TaskResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.sonarqube.ws.WsCe.TaskResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>optional string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object taskType_ = "";
      /**
       * <code>optional string taskType = 2;</code>
       */
      public java.lang.String getTaskType() {
        java.lang.Object ref = taskType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            taskType_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string taskType = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTaskTypeBytes() {
        java.lang.Object ref = taskType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          taskType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string taskType = 2;</code>
       */
      public Builder setTaskType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        taskType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string taskType = 2;</code>
       */
      public Builder clearTaskType() {
        
        taskType_ = getDefaultInstance().getTaskType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string taskType = 2;</code>
       */
      public Builder setTaskTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        taskType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object componentId_ = "";
      /**
       * <code>optional string componentId = 3;</code>
       */
      public java.lang.String getComponentId() {
        java.lang.Object ref = componentId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            componentId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string componentId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getComponentIdBytes() {
        java.lang.Object ref = componentId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          componentId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string componentId = 3;</code>
       */
      public Builder setComponentId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        componentId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string componentId = 3;</code>
       */
      public Builder clearComponentId() {
        
        componentId_ = getDefaultInstance().getComponentId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string componentId = 3;</code>
       */
      public Builder setComponentIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        componentId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object componentKey_ = "";
      /**
       * <code>optional string componentKey = 4;</code>
       */
      public java.lang.String getComponentKey() {
        java.lang.Object ref = componentKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            componentKey_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string componentKey = 4;</code>
       */
      public com.google.protobuf.ByteString
          getComponentKeyBytes() {
        java.lang.Object ref = componentKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          componentKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string componentKey = 4;</code>
       */
      public Builder setComponentKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        componentKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string componentKey = 4;</code>
       */
      public Builder clearComponentKey() {
        
        componentKey_ = getDefaultInstance().getComponentKey();
        onChanged();
        return this;
      }
      /**
       * <code>optional string componentKey = 4;</code>
       */
      public Builder setComponentKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        componentKey_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object componentName_ = "";
      /**
       * <code>optional string componentName = 5;</code>
       */
      public java.lang.String getComponentName() {
        java.lang.Object ref = componentName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            componentName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string componentName = 5;</code>
       */
      public com.google.protobuf.ByteString
          getComponentNameBytes() {
        java.lang.Object ref = componentName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          componentName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string componentName = 5;</code>
       */
      public Builder setComponentName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        componentName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string componentName = 5;</code>
       */
      public Builder clearComponentName() {
        
        componentName_ = getDefaultInstance().getComponentName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string componentName = 5;</code>
       */
      public Builder setComponentNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        componentName_ = value;
        onChanged();
        return this;
      }

      private int status_ = 0;
      /**
       * <code>optional .sonarqube.ws.ce.TaskStatus status = 6;</code>
       */
      public int getStatusValue() {
        return status_;
      }
      /**
       * <code>optional .sonarqube.ws.ce.TaskStatus status = 6;</code>
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .sonarqube.ws.ce.TaskStatus status = 6;</code>
       */
      public org.sonarqube.ws.WsCe.TaskStatus getStatus() {
        org.sonarqube.ws.WsCe.TaskStatus result = org.sonarqube.ws.WsCe.TaskStatus.valueOf(status_);
        return result == null ? org.sonarqube.ws.WsCe.TaskStatus.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .sonarqube.ws.ce.TaskStatus status = 6;</code>
       */
      public Builder setStatus(org.sonarqube.ws.WsCe.TaskStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .sonarqube.ws.ce.TaskStatus status = 6;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object submittedAt_ = "";
      /**
       * <code>optional string submittedAt = 7;</code>
       */
      public java.lang.String getSubmittedAt() {
        java.lang.Object ref = submittedAt_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            submittedAt_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string submittedAt = 7;</code>
       */
      public com.google.protobuf.ByteString
          getSubmittedAtBytes() {
        java.lang.Object ref = submittedAt_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          submittedAt_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string submittedAt = 7;</code>
       */
      public Builder setSubmittedAt(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        submittedAt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string submittedAt = 7;</code>
       */
      public Builder clearSubmittedAt() {
        
        submittedAt_ = getDefaultInstance().getSubmittedAt();
        onChanged();
        return this;
      }
      /**
       * <code>optional string submittedAt = 7;</code>
       */
      public Builder setSubmittedAtBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        submittedAt_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object submitterLogin_ = "";
      /**
       * <code>optional string submitterLogin = 8;</code>
       */
      public java.lang.String getSubmitterLogin() {
        java.lang.Object ref = submitterLogin_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            submitterLogin_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string submitterLogin = 8;</code>
       */
      public com.google.protobuf.ByteString
          getSubmitterLoginBytes() {
        java.lang.Object ref = submitterLogin_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          submitterLogin_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string submitterLogin = 8;</code>
       */
      public Builder setSubmitterLogin(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        submitterLogin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string submitterLogin = 8;</code>
       */
      public Builder clearSubmitterLogin() {
        
        submitterLogin_ = getDefaultInstance().getSubmitterLogin();
        onChanged();
        return this;
      }
      /**
       * <code>optional string submitterLogin = 8;</code>
       */
      public Builder setSubmitterLoginBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        submitterLogin_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object startedAt_ = "";
      /**
       * <code>optional string startedAt = 9;</code>
       */
      public java.lang.String getStartedAt() {
        java.lang.Object ref = startedAt_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            startedAt_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string startedAt = 9;</code>
       */
      public com.google.protobuf.ByteString
          getStartedAtBytes() {
        java.lang.Object ref = startedAt_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          startedAt_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string startedAt = 9;</code>
       */
      public Builder setStartedAt(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        startedAt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string startedAt = 9;</code>
       */
      public Builder clearStartedAt() {
        
        startedAt_ = getDefaultInstance().getStartedAt();
        onChanged();
        return this;
      }
      /**
       * <code>optional string startedAt = 9;</code>
       */
      public Builder setStartedAtBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        startedAt_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object finishedAt_ = "";
      /**
       * <code>optional string finishedAt = 10;</code>
       */
      public java.lang.String getFinishedAt() {
        java.lang.Object ref = finishedAt_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            finishedAt_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string finishedAt = 10;</code>
       */
      public com.google.protobuf.ByteString
          getFinishedAtBytes() {
        java.lang.Object ref = finishedAt_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          finishedAt_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string finishedAt = 10;</code>
       */
      public Builder setFinishedAt(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        finishedAt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string finishedAt = 10;</code>
       */
      public Builder clearFinishedAt() {
        
        finishedAt_ = getDefaultInstance().getFinishedAt();
        onChanged();
        return this;
      }
      /**
       * <code>optional string finishedAt = 10;</code>
       */
      public Builder setFinishedAtBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        finishedAt_ = value;
        onChanged();
        return this;
      }

      private boolean isLastFinished_ ;
      /**
       * <code>optional bool isLastFinished = 11;</code>
       */
      public boolean getIsLastFinished() {
        return isLastFinished_;
      }
      /**
       * <code>optional bool isLastFinished = 11;</code>
       */
      public Builder setIsLastFinished(boolean value) {
        
        isLastFinished_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool isLastFinished = 11;</code>
       */
      public Builder clearIsLastFinished() {
        
        isLastFinished_ = false;
        onChanged();
        return this;
      }

      private long executionTimeMs_ ;
      /**
       * <code>optional int64 executionTimeMs = 12;</code>
       */
      public long getExecutionTimeMs() {
        return executionTimeMs_;
      }
      /**
       * <code>optional int64 executionTimeMs = 12;</code>
       */
      public Builder setExecutionTimeMs(long value) {
        
        executionTimeMs_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 executionTimeMs = 12;</code>
       */
      public Builder clearExecutionTimeMs() {
        
        executionTimeMs_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:sonarqube.ws.ce.TaskResponse)
    }

    // @@protoc_insertion_point(class_scope:sonarqube.ws.ce.TaskResponse)
    private static final org.sonarqube.ws.WsCe.TaskResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.sonarqube.ws.WsCe.TaskResponse();
    }

    public static org.sonarqube.ws.WsCe.TaskResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<TaskResponse> PARSER =
        new com.google.protobuf.AbstractParser<TaskResponse>() {
      public TaskResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new TaskResponse(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TaskResponse> getParserForType() {
      return PARSER;
    }

    public org.sonarqube.ws.WsCe.TaskResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ProjectResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sonarqube.ws.ce.ProjectResponse)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code sonarqube.ws.ce.ProjectResponse}
   *
   * <pre>
   * GET api/ce/project
   * </pre>
   */
  public  static final class ProjectResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:sonarqube.ws.ce.ProjectResponse)
      ProjectResponseOrBuilder {
    // Use ProjectResponse.newBuilder() to construct.
    private ProjectResponse(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private ProjectResponse() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ProjectResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.sonarqube.ws.WsCe.internal_static_sonarqube_ws_ce_ProjectResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.sonarqube.ws.WsCe.internal_static_sonarqube_ws_ce_ProjectResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.sonarqube.ws.WsCe.ProjectResponse.class, org.sonarqube.ws.WsCe.ProjectResponse.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static org.sonarqube.ws.WsCe.ProjectResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sonarqube.ws.WsCe.ProjectResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sonarqube.ws.WsCe.ProjectResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sonarqube.ws.WsCe.ProjectResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sonarqube.ws.WsCe.ProjectResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.sonarqube.ws.WsCe.ProjectResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.sonarqube.ws.WsCe.ProjectResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.sonarqube.ws.WsCe.ProjectResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.sonarqube.ws.WsCe.ProjectResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.sonarqube.ws.WsCe.ProjectResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.sonarqube.ws.WsCe.ProjectResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sonarqube.ws.ce.ProjectResponse}
     *
     * <pre>
     * GET api/ce/project
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sonarqube.ws.ce.ProjectResponse)
        org.sonarqube.ws.WsCe.ProjectResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.sonarqube.ws.WsCe.internal_static_sonarqube_ws_ce_ProjectResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.sonarqube.ws.WsCe.internal_static_sonarqube_ws_ce_ProjectResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.sonarqube.ws.WsCe.ProjectResponse.class, org.sonarqube.ws.WsCe.ProjectResponse.Builder.class);
      }

      // Construct using org.sonarqube.ws.WsCe.ProjectResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.sonarqube.ws.WsCe.internal_static_sonarqube_ws_ce_ProjectResponse_descriptor;
      }

      public org.sonarqube.ws.WsCe.ProjectResponse getDefaultInstanceForType() {
        return org.sonarqube.ws.WsCe.ProjectResponse.getDefaultInstance();
      }

      public org.sonarqube.ws.WsCe.ProjectResponse build() {
        org.sonarqube.ws.WsCe.ProjectResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.sonarqube.ws.WsCe.ProjectResponse buildPartial() {
        org.sonarqube.ws.WsCe.ProjectResponse result = new org.sonarqube.ws.WsCe.ProjectResponse(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.sonarqube.ws.WsCe.ProjectResponse) {
          return mergeFrom((org.sonarqube.ws.WsCe.ProjectResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.sonarqube.ws.WsCe.ProjectResponse other) {
        if (other == org.sonarqube.ws.WsCe.ProjectResponse.getDefaultInstance()) return this;
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.sonarqube.ws.WsCe.ProjectResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.sonarqube.ws.WsCe.ProjectResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:sonarqube.ws.ce.ProjectResponse)
    }

    // @@protoc_insertion_point(class_scope:sonarqube.ws.ce.ProjectResponse)
    private static final org.sonarqube.ws.WsCe.ProjectResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.sonarqube.ws.WsCe.ProjectResponse();
    }

    public static org.sonarqube.ws.WsCe.ProjectResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<ProjectResponse> PARSER =
        new com.google.protobuf.AbstractParser<ProjectResponse>() {
      public ProjectResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new ProjectResponse(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ProjectResponse> getParserForType() {
      return PARSER;
    }

    public org.sonarqube.ws.WsCe.ProjectResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sonarqube_ws_ce_SubmitResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sonarqube_ws_ce_SubmitResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sonarqube_ws_ce_TaskResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sonarqube_ws_ce_TaskResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sonarqube_ws_ce_ProjectResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sonarqube_ws_ce_ProjectResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013ws-ce.proto\022\017sonarqube.ws.ce\" \n\016Submit" +
      "Response\022\016\n\006taskId\030\001 \001(\t\"\240\002\n\014TaskRespons" +
      "e\022\n\n\002id\030\001 \001(\t\022\020\n\010taskType\030\002 \001(\t\022\023\n\013compo" +
      "nentId\030\003 \001(\t\022\024\n\014componentKey\030\004 \001(\t\022\025\n\rco" +
      "mponentName\030\005 \001(\t\022+\n\006status\030\006 \001(\0162\033.sona" +
      "rqube.ws.ce.TaskStatus\022\023\n\013submittedAt\030\007 " +
      "\001(\t\022\026\n\016submitterLogin\030\010 \001(\t\022\021\n\tstartedAt" +
      "\030\t \001(\t\022\022\n\nfinishedAt\030\n \001(\t\022\026\n\016isLastFini" +
      "shed\030\013 \001(\010\022\027\n\017executionTimeMs\030\014 \001(\003\"\021\n\017P" +
      "rojectResponse*Q\n\nTaskStatus\022\013\n\007PENDING\020",
      "\000\022\017\n\013IN_PROGRESS\020\001\022\013\n\007SUCCESS\020\002\022\n\n\006FAILE" +
      "D\020\003\022\014\n\010CANCELED\020\004B\032\n\020org.sonarqube.wsB\004W" +
      "sCeH\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_sonarqube_ws_ce_SubmitResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sonarqube_ws_ce_SubmitResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sonarqube_ws_ce_SubmitResponse_descriptor,
        new java.lang.String[] { "TaskId", });
    internal_static_sonarqube_ws_ce_TaskResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_sonarqube_ws_ce_TaskResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sonarqube_ws_ce_TaskResponse_descriptor,
        new java.lang.String[] { "Id", "TaskType", "ComponentId", "ComponentKey", "ComponentName", "Status", "SubmittedAt", "SubmitterLogin", "StartedAt", "FinishedAt", "IsLastFinished", "ExecutionTimeMs", });
    internal_static_sonarqube_ws_ce_ProjectResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_sonarqube_ws_ce_ProjectResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_sonarqube_ws_ce_ProjectResponse_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
